# Databricks notebook source
# MAGIC %md
# MAGIC ## Accelerating analytics with DatabricksIQ - In the SQL Editor
# MAGIC
# MAGIC In the previous notebook we used one of the components of DatabricksIQ - the Assistant - to transform IMDb data and save it to a table in Unity Catalog.  We then used the _AI generate_ features in Unity Catalog to add metadata describing the table and its columns.  Now we turn our attention to analyzing the data with Databricks SQL from inside the SQL Editor. 

# COMMAND ----------

# MAGIC %md
# MAGIC ### Finding tables with the Assistant
# MAGIC
# MAGIC You can use natural language or shortcuts to tell the Assistant to find tables related to your subject.  <br>
# MAGIC
# MAGIC **Prompt:** <br>
# MAGIC _/findTables about box office performance_ <br><br>
# MAGIC
# MAGIC <img src="https://github.com/RafiKurlansik/notebook2/blob/main/assets/findtables_sqleditor.gif?raw=true" width=800>
# MAGIC
# MAGIC Clicking on the `movies` table, the Assistant gives us a few choices of how to proceed with the data:
# MAGIC
# MAGIC 1. **Suggest a few starter SQL queries**
# MAGIC 2. **Describe the table**
# MAGIC 3. **Query the table using natural language**
# MAGIC
# MAGIC Let's explore each of these options.
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ### Suggest SELECT queries
# MAGIC
# MAGIC If you aren't sure where to start, the Assistant will give you a few sample SQL queries to run. <br><br>
# MAGIC
# MAGIC <img src="https://github.com/RafiKurlansik/notebook2/blob/main/assets/suggest_select_sql.gif?raw=true">
# MAGIC <br><br>
# MAGIC
# MAGIC Notice how the Assistant is ready to provide a handy name for our query, taking some of the tedium out of crafting our queries.

# COMMAND ----------

# MAGIC %md
# MAGIC ### Describe table
# MAGIC Choosing the describe option will return a description of the table based on metadata available in Unity Catalog, including the description and annotation that were generated by AI in previous steps.
# MAGIC
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ### Querying with natural language
# MAGIC
# MAGIC Asking questions of the data in your lakehouse using natural language is now possible with DatabricksIQ and the Assistant.  <br><br>
# MAGIC
# MAGIC <img src="https://github.com/RafiKurlansik/notebook2/blob/main/assets/text2sql.gif?raw=true" width=1100>
# MAGIC
# MAGIC Note the following:
# MAGIC
# MAGIC * Selecting _Query in natural language_ prompts the Assitant to use the table for any follow up queries
# MAGIC * The Assistant explains its reasoning behind the generated SQL

# COMMAND ----------

# MAGIC %md
# MAGIC ### Genie Data Rooms (Private Preview)
# MAGIC
# MAGIC Let's continue our journey by creating a Genie Data Room to have a conversation with our data using generative AI.  This is a perfect way to open up Databricks to non-technical users.  
# MAGIC
# MAGIC To create a data room, we navigate to the table we want to analyze in the Catalog Explorer.  By clicking on _Create_, we see the option to create a Genie Data Room in the drop down menu.<br><br>
# MAGIC
# MAGIC <img src="https://github.com/RafiKurlansik/notebook2/blob/main/assets/create_genie.gif?raw=true" width=700>

# COMMAND ----------

# MAGIC %md
# MAGIC #### Setting up the room
# MAGIC
# MAGIC Preparing a data room for Genie is simple and can be done in a few steps.

# COMMAND ----------

# MAGIC %md ##### Select tables and compute
# MAGIC
# MAGIC <br><br>
# MAGIC <img src="https://github.com/RafiKurlansik/notebook2/blob/main/assets/setup_room.gif?raw=true" width=800>
# MAGIC

# COMMAND ----------

# MAGIC %md ##### Add custom instructions (optional) 
# MAGIC <br><br>
# MAGIC <img src="https://github.com/RafiKurlansik/notebook2/blob/main/assets/instructions.gif?raw=true" width=800>

# COMMAND ----------

# MAGIC %md ##### Ask questions in natural language
# MAGIC <br><br>
# MAGIC <img src="https://github.com/RafiKurlansik/notebook2/blob/main/assets/genie_question.gif?raw=true" width = 800>
# MAGIC <br><br>
# MAGIC Genie is able to automatically generate visualizations for you, or you can ask for a specific kind of visualization.
# MAGIC <br><br>
# MAGIC
# MAGIC <img src="https://github.com/RafiKurlansik/notebook2/blob/main/assets/genie_autovisualize.gif?raw=true" width=800>

# COMMAND ----------


